Repository Swap-Subnet/swap-subnet, pull requests merged in 2025-04, with the labels that each got.

#89 Release 2.2.9
  min_compute.yml
  sturdy/__init__.py
  sturdy/constants.py
  sturdy/validator/apy_binning.py
  sturdy/validator/reward.py
  tests/unit/validator/test_reward_helpers.py
Labels: release

#90 Add dynamic bin threshold
  min_compute.yml
  sturdy/__init__.py
  sturdy/constants.py
  sturdy/validator/apy_binning.py
  tests/unit/validator/test_reward_helpers.py
Labels: enhancement, fix

#91 Release/2.2.10
  min_compute.yml
  sturdy/__init__.py
  sturdy/constants.py
  sturdy/validator/apy_binning.py
  sturdy/validator/reward.py
  tests/unit/validator/test_reward_helpers.py
Labels: release

#98 Release 3.0.2
  docs/api_usage.md
  docs/validator.md
  min_compute.yml
  neurons/validator.py
  sturdy/__init__.py
  sturdy/protocol.py
  sturdy/validator/forward.py
  sturdy/validator/reward.py
  sturdy/validator/sql.py
Labels: enhancement, release

#100 Dockerize Validator with Watchtower
  .dockerignore
  .github/docker.yml
  .gitignore
  Dockerfile
  docker-compose.yml
  docker-entrypoint.sh
Labels: enhancement

#103 Release 3.0.3
  .env.example
  min_compute.yml
  neurons/validator.py
  sturdy/__init__.py
  sturdy/constants.py
Labels: release

#104 chore: update validator docs
  docs/validator.md
Labels: fix
